### ISSUE TITLE
questions about the test result

### ISSUE THREAD

**Issue by chengcheng8632** [facebookresearch/mvfst-rl#15]
Dear Author:
I think I have successfully built the mvfst-rl environment with your help. Thank you very much. Then I used the model in the model file to test it in pantheon. But I found that the environmental condition at "mm-delay 30 mm-link 12mbps.trace 12mbps.trace --uplink-queue=droptail --uplink-queue-args=bytes= 90000" or other environmental conditions, mvfst-rl has a higher throughput, but the packet loss rate is also high. The results are as follows table:

scheme#   runs	mean avg tput (Mbit/s)  mean 95th-%ile delay (ms) mean loss rate (%)  
TCP BBR	3	             11.69	                                       67.85	                           0.65
TCP Cubic	3	             11.92	                                       88.64	                           0.35
FillP	        3	              7.56	                                               89.23	                          14.63
FillP-Sheep	3	              8.01	                                               86.73	                           4.61
Indigo	        3	              11.36	                                       40.14	                           0.13
LEDBAT	3	              11.33	                                       89.38	                           0.24
mvfst-bbr	3	              11.91	                                       91.19	                          48.06
mvfst-copa	3	               2.86	                                       38.67	                          0.11
mvfst-rl	3	               11.87	                                       91.39	                          86.5
PCC-Allegro3	               10.04	                                       33.23	                          0.89
PCC-Expr	3	               10.91	                                        81.76	                          1.41
PCC-Vivace	3	                10.9	                                        37.12	                          0.11

I want to know if the result of this is that my environment is not configured correctly, or the model that we train through reinforcement learning is not very friendly to this network condition? Could you give me the pantheon test report for reference? My email address is: chengcheng8632@163.com
I look forward to your answer, thank you again.

**Comment by viswanathgs** [comment]
Hi @chengcheng8632! Glad to hear that you got the environment working. I wouldn't be surprised if the loss rate is also higher for these environments. The model file in the src dir doesn't yet generalize to all environments available. As long as mahimahi, etc., are installed correctly, what you see wouldn't be a result of bad configuration as the experiments are performed inside a tunnel. I would encourage running a full training with the specific network emulator(s) that interest you instead of relying on the model file released. Hope this helps.
