### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by BetterYong** [facebookresearch/mvfst-rl#17]
Hello, I read your article carefully and am very interested in this project. I want to run and test this project, but I encountered some problems when I ran it. When I input “ ./setup.sh --inference”
line 39 ./setup.sh: 行 39: POSITIONAL[@]: Unbound variable
then i did " #set -- "${POSITIONAL[@]}" # Restore positional parameters"
then i get 
"
Inference-only build
Installing libtorch CPU-only build into /home/python/mvfst-rl-master/_build/deps/libtorch
2019-12-01 02:48:17 URL:https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.2.0.zip [81767660/81767660] -> "libtorch-cxx11-abi-shared-with-deps-1.2.0.zip.7" [1]
Archive:  libtorch-cxx11-abi-shared-with-deps-1.2.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of libtorch-cxx11-abi-shared-with-deps-1.2.0.zip or
        libtorch-cxx11-abi-shared-with-deps-1.2.0.zip.zip, and cannot find libtorch-cxx11-abi-shared-with-deps-1.2.0.zip.ZIP, period.
"
What should I do to run this project？Looking forward to hearing from you

**Comment by odelalleau** [comment]
Could it simply be that the It looks like the libtorch-cxx11-abi-shared-with-deps-1.2.0.zip file you downloaded got corrupted somehow? Try to re-download it (not sure if you'll need to delete a cached local version first...)

**Comment by odelalleau** [comment]
I am going to close this issue for now, please re-open if this is still a problem.
