### ISSUE TITLE
questions about fairness

### ISSUE THREAD

**Issue by chengcheng8632** [facebookresearch/mvfst-rl#19]
Dear Author:
I'm sorry to bother you. I want to further analyze mvfst-rl. I want to know if fairness is considered when designing algorithms and training models. If so, how did you do it? Looking forward to your answer. Best wishes!

**Comment by viswanathgs** [comment]
Hi @chengcheng8632, we haven't done work on fairness yet for the initial set of experiments and release. We plan to do that in the future though. cc @odelalleau.
