### ISSUE TITLE
Questions about models

### ISSUE THREAD

**Issue by chengcheng8632** [facebookresearch/mvfst-rl#20]
Dear author,
        Sorry to bother you, I want to use your trained reinforcement learning model for congestion experiments in the actual environment, instead of testing in pantheon. However, I found that on the one hand, when the delay reached 40ms, the model could not control it. On the other hand, when there is no time delay, the value of cwnd has been increasing at a rate of 2 times, until it reaches the maximum value we set (even if we set the value to be large), I feel this phenomenon is a bit strange. May I ask the author if your model has been tested in an actual environment. Whether the two phenomena above normal will occur? Looking forward to your answer, thank you!

**Comment by viswanathgs** [comment]
Hey @chengcheng8632, thanks for trying this out in an actual network, this is exciting!

We haven't done that yet, but @odelalleau is working on getting that up. Your observations are quite valuable. The second one where the cwnd keeps increasing when there is no delay should be what we want right, since in the case of no delay, we want to achieve as much throughput as we can. The first phenomenon though is certainly not expected. Could you share exactly what the behavior was when the delay reached 40ms? What was the corresponding throughput? Did the model continue to increase cwnd despite a higher delay and lower throughput?

**Comment by chengcheng8632** [comment]
Hello,@viswanathgs,thank you for your answer. I tested it with mvfst under 1000Mbps bandwidth. Our experiments show that under the circumstance of delay, cwnd will increase by 2 times, but it will not work at 40ms. 
#########The following is log at 40ms delay:##########
I0309 10:31:13.627102 67732 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.286886 MB/sec, avg delay = 0.6655 ms, max delay = 1.331 ms, total Mb lost = 0, reward = 0.0206862
I0309 10:31:13.836073 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 90.6714 ms
I0309 10:31:13.856302 67732 CongestionControlEnv.cpp:169] Num states = 4 avg throughput = 0.203379 MB/sec, avg delay = 42.6575 ms, max delay = 90.878 ms, total Mb lost = 0, reward = -17.9722
I0309 10:31:13.902532 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 45.263 ms
I0309 10:31:13.966622 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309437 MB/sec, avg delay = 0.0876667 ms, max delay = 0.133 ms, total Mb lost = 0, reward = 0.282837
I0309 10:31:13.972993 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.28406 ms
I0309 10:31:14.076683 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309085 MB/sec, avg delay = 0.133667 ms, max delay = 0.149 ms, total Mb lost = 0, reward = 0.279285
I0309 10:31:14.083355 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.60193 ms
I0309 10:31:14.190090 67732 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.308934 MB/sec, avg delay = 0.1535 ms, max delay = 0.155 ms, total Mb lost = 0, reward = 0.277934
I0309 10:31:14.196816 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.70031 ms
I0309 10:31:14.302036 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.30933 MB/sec, avg delay = 0.101667 ms, max delay = 0.147 ms, total Mb lost = 0, reward = 0.27993
I0309 10:31:14.308727 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.68444 ms
I0309 10:31:14.414017 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309269 MB/sec, avg delay = 0.109667 ms, max delay = 0.149 ms, total Mb lost = 0, reward = 0.279469
I0309 10:31:14.420578 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.47538 ms
I0309 10:31:14.530133 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309113 MB/sec, avg delay = 0.13 ms, max delay = 0.147 ms, total Mb lost = 0, reward = 0.279713
I0309 10:31:14.536693 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.55397 ms
I0309 10:31:14.644101 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309095 MB/sec, avg delay = 0.132333 ms, max delay = 0.152 ms, total Mb lost = 0, reward = 0.278695
I0309 10:31:14.650952 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.74046 ms
I0309 10:31:14.757602 67732 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.308957 MB/sec, avg delay = 0.1505 ms, max delay = 0.154 ms, total Mb lost = 0, reward = 0.278157
I0309 10:31:14.764564 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.90375 ms
I0309 10:31:14.863477 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309398 MB/sec, avg delay = 0.0926667 ms, max delay = 0.144 ms, total Mb lost = 0, reward = 0.280598
I0309 10:31:14.870442 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.92722 ms
I0309 10:31:14.973661 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309039 MB/sec, avg delay = 0.139667 ms, max delay = 0.147 ms, total Mb lost = 0, reward = 0.279639
I0309 10:31:14.980523 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.84708 ms
I0309 10:31:15.087054 67732 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.309002 MB/sec, avg delay = 0.1445 ms, max delay = 0.158 ms, total Mb lost = 0, reward = 0.277402
I0309 10:31:15.093608 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.52605 ms
I0309 10:31:15.197978 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.307209 MB/sec, avg delay = 0.384333 ms, max delay = 0.903 ms, total Mb lost = 0, reward = 0.126609
I0309 10:31:15.205037 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 6.01972 ms
I0309 10:31:15.301786 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309192 MB/sec, avg delay = 0.119667 ms, max delay = 0.142 ms, total Mb lost = 0, reward = 0.280792
I0309 10:31:15.308768 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.66299 ms
I0309 10:31:15.413621 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.308986 MB/sec, avg delay = 0.146667 ms, max delay = 0.161 ms, total Mb lost = 0, reward = 0.276786
I0309 10:31:15.420485 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.64904 ms
I0309 10:31:15.530905 67732 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.30904 MB/sec, avg delay = 0.1395 ms, max delay = 0.14 ms, total Mb lost = 0, reward = 0.28104
I0309 10:31:15.537215 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.23427 ms
I0309 10:31:15.640571 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309082 MB/sec, avg delay = 0.134 ms, max delay = 0.152 ms, total Mb lost = 0, reward = 0.278682
I0309 10:31:15.647174 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.55261 ms
I0309 10:31:15.756682 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.308953 MB/sec, avg delay = 0.151 ms, max delay = 0.167 ms, total Mb lost = 0, reward = 0.275553
I0309 10:31:15.762977 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.2149 ms
I0309 10:31:15.862238 67732 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.308999 MB/sec, avg delay = 0.145 ms, max delay = 0.147 ms, total Mb lost = 0, reward = 0.279599
I0309 10:31:15.868429 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.15603 ms
I0309 10:31:15.979365 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.307098 MB/sec, avg delay = 0.4 ms, max delay = 0.988 ms, total Mb lost = 0, reward = 0.109498
I0309 10:31:15.985416 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.01398 ms
I0309 10:31:16.095379 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309468 MB/sec, avg delay = 0.0836667 ms, max delay = 0.146 ms, total Mb lost = 0, reward = 0.280268
I0309 10:31:16.102327 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.85925 ms
I0309 10:31:16.208954 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309301 MB/sec, avg delay = 0.105333 ms, max delay = 0.112 ms, total Mb lost = 0, reward = 0.286901
I0309 10:31:16.215206 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.06474 ms
I0309 10:31:16.321039 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309082 MB/sec, avg delay = 0.134 ms, max delay = 0.153 ms, total Mb lost = 0, reward = 0.278482
I0309 10:31:16.327167 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 5.05673 ms
I0309 10:31:16.441081 67732 CongestionControlEnv.cpp:169] Num states = 3 avg throughput = 0.309149 MB/sec, avg delay = 0.125333 ms, max delay = 0.147 ms, total Mb lost = 0, reward = 0.279749
I0309 10:31:16.446780 67732 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 4.64994 ms


#########The following is log at 20ms delay:#########
I0309 14:31:03.612912 18403 CongestionControlEnv.cpp:169] Num states = 2 avg throughput = 0.285727 MB/sec, avg delay = 0.6715 ms, max delay = 1.343 ms, total Mb lost = 0, reward = 0.0171273
I0309 14:31:03.803530 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 89.1498 ms
I0309 14:31:03.819335 18403 CongestionControlEnv.cpp:169] Num states = 7 avg throughput = 0.469508 MB/sec, avg delay = 20.2911 ms, max delay = 73.94 ms, total Mb lost = 0, reward = -14.3185
I0309 14:31:03.866426 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=0, cwnd=10), policy elapsed time = 46.2541 ms
I0309 14:31:03.930668 18403 CongestionControlEnv.cpp:169] Num states = 5 avg throughput = 0.610864 MB/sec, avg delay = 0.1376 ms, max delay = 0.157 ms, total Mb lost = 0, reward = 0.579464
I0309 14:31:03.936614 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=20), policy elapsed time = 5.05231 ms
I0309 14:31:04.042162 18403 CongestionControlEnv.cpp:169] Num states = 9 avg throughput = 1.22242 MB/sec, avg delay = 0.153778 ms, max delay = 0.196 ms, total Mb lost = 0, reward = 1.18322
I0309 14:31:04.048799 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=40), policy elapsed time = 5.58504 ms
I0309 14:31:04.150010 18403 CongestionControlEnv.cpp:169] Num states = 20 avg throughput = 2.32964 MB/sec, avg delay = 0.0837 ms, max delay = 0.168 ms, total Mb lost = 0, reward = 2.29604
I0309 14:31:04.156611 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=80), policy elapsed time = 5.62984 ms
I0309 14:31:04.264459 18403 CongestionControlEnv.cpp:169] Num states = 22 avg throughput = 4.90802 MB/sec, avg delay = 0.123455 ms, max delay = 0.217 ms, total Mb lost = 0, reward = 4.86462
I0309 14:31:04.271190 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=160), policy elapsed time = 5.68795 ms
I0309 14:31:04.369737 18403 CongestionControlEnv.cpp:169] Num states = 34 avg throughput = 9.83344 MB/sec, avg delay = 0.124471 ms, max delay = 0.417 ms, total Mb lost = 0, reward = 9.75004
I0309 14:31:04.376700 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=320), policy elapsed time = 5.98537 ms
I0309 14:31:04.482569 18403 CongestionControlEnv.cpp:169] Num states = 76 avg throughput = 19.1857 MB/sec, avg delay = 0.179921 ms, max delay = 0.739 ms, total Mb lost = 0, reward = 19.0379
I0309 14:31:04.489166 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=640), policy elapsed time = 5.5294 ms
I0309 14:31:04.589463 18403 CongestionControlEnv.cpp:169] Num states = 120 avg throughput = 37.6675 MB/sec, avg delay = 0.237142 ms, max delay = 0.958 ms, total Mb lost = 0, reward = 37.4759
I0309 14:31:04.596138 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=1280), policy elapsed time = 5.55944 ms
I0309 14:31:04.706264 18403 CongestionControlEnv.cpp:169] Num states = 166 avg throughput = 78.0281 MB/sec, avg delay = 0.435717 ms, max delay = 1.651 ms, total Mb lost = 0, reward = 77.6979
I0309 14:31:04.713042 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=2560), policy elapsed time = 5.72502 ms
I0309 14:31:04.821813 18403 CongestionControlEnv.cpp:169] Num states = 228 avg throughput = 152.057 MB/sec, avg delay = 0.911904 ms, max delay = 2.353 ms, total Mb lost = 2.0032, reward = 151.587
I0309 14:31:04.828537 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=5120), policy elapsed time = 5.52197 ms
I0309 14:31:04.929446 18403 CongestionControlEnv.cpp:169] Num states = 307 avg throughput = 289.481 MB/sec, avg delay = 1.82743 ms, max delay = 2.746 ms, total Mb lost = 12.3497, reward = 288.932
I0309 14:31:04.935896 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=10240), policy elapsed time = 5.31859 ms
I0309 14:31:05.045447 18403 CongestionControlEnv.cpp:169] Num states = 338 avg throughput = 589.661 MB/sec, avg delay = 2.08482 ms, max delay = 8.83 ms, total Mb lost = 14.0963, reward = 587.895
I0309 14:31:05.051409 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=20480), policy elapsed time = 5.10529 ms
I0309 14:31:05.161468 18403 CongestionControlEnv.cpp:169] Num states = 308 avg throughput = 1140.92 MB/sec, avg delay = 1.95897 ms, max delay = 2.603 ms, total Mb lost = 17.7909, reward = 1140.4
I0309 14:31:05.167886 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=40960), policy elapsed time = 5.30162 ms
I0309 14:31:05.273444 18403 CongestionControlEnv.cpp:169] Num states = 277 avg throughput = 2320.82 MB/sec, avg delay = 1.93324 ms, max delay = 2.608 ms, total Mb lost = 17.7609, reward = 2320.3
I0309 14:31:05.279537 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=81920), policy elapsed time = 5.19426 ms
I0309 14:31:05.381458 18403 CongestionControlEnv.cpp:169] Num states = 268 avg throughput = 4627.91 MB/sec, avg delay = 1.92328 ms, max delay = 2.904 ms, total Mb lost = 16.9871, reward = 4627.33
I0309 14:31:05.387725 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=163840), policy elapsed time = 5.19901 ms
I0309 14:31:05.493448 18403 CongestionControlEnv.cpp:169] Num states = 238 avg throughput = 9150.74 MB/sec, avg delay = 2.08552 ms, max delay = 6.076 ms, total Mb lost = 17.6081, reward = 9149.52
I0309 14:31:05.499809 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=327680), policy elapsed time = 5.43773 ms
I0309 14:31:05.597487 18403 CongestionControlEnv.cpp:169] Num states = 235 avg throughput = 18489.4 MB/sec, avg delay = 1.97891 ms, max delay = 3.031 ms, total Mb lost = 15.7301, reward = 18488.8
I0309 14:31:05.603211 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=655360), policy elapsed time = 4.89243 ms
I0309 14:31:05.717459 18403 CongestionControlEnv.cpp:169] Num states = 321 avg throughput = 36938 MB/sec, avg delay = 1.93523 ms, max delay = 2.929 ms, total Mb lost = 19.0567, reward = 36937.4
I0309 14:31:05.723112 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.70048 ms
I0309 14:31:05.833441 18403 CongestionControlEnv.cpp:169] Num states = 338 avg throughput = 48910.9 MB/sec, avg delay = 1.96656 ms, max delay = 3.6 ms, total Mb lost = 17.1273, reward = 48910.1
I0309 14:31:05.839654 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 5.15963 ms
I0309 14:31:05.937924 18403 CongestionControlEnv.cpp:169] Num states = 299 avg throughput = 49513.9 MB/sec, avg delay = 2.22141 ms, max delay = 6.398 ms, total Mb lost = 15.2569, reward = 49512.6
I0309 14:31:05.943917 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.9596 ms
I0309 14:31:06.057487 18403 CongestionControlEnv.cpp:169] Num states = 346 avg throughput = 49792.8 MB/sec, avg delay = 2.05934 ms, max delay = 4.916 ms, total Mb lost = 18.6623, reward = 49791.9
I0309 14:31:06.063432 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.84464 ms
I0309 14:31:06.173676 18403 CongestionControlEnv.cpp:169] Num states = 321 avg throughput = 49743.3 MB/sec, avg delay = 1.92084 ms, max delay = 3.369 ms, total Mb lost = 17.0009, reward = 49742.6
I0309 14:31:06.179606 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.87198 ms
I0309 14:31:06.277626 18403 CongestionControlEnv.cpp:169] Num states = 304 avg throughput = 49558.5 MB/sec, avg delay = 2.10016 ms, max delay = 3.948 ms, total Mb lost = 16.2572, reward = 49557.7
I0309 14:31:06.283331 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.82899 ms
I0309 14:31:06.393455 18403 CongestionControlEnv.cpp:169] Num states = 305 avg throughput = 49709.2 MB/sec, avg delay = 2.02676 ms, max delay = 3.176 ms, total Mb lost = 17.1486, reward = 49708.5
I0309 14:31:06.399442 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.90785 ms
I0309 14:31:06.501456 18403 CongestionControlEnv.cpp:169] Num states = 275 avg throughput = 49868.1 MB/sec, avg delay = 1.93138 ms, max delay = 2.741 ms, total Mb lost = 16.4863, reward = 49867.5
I0309 14:31:06.507295 18403 CongestionControlEnv.cpp:51] Action updated (cwndAction=4, cwnd=860000), policy elapsed time = 4.72928 ms




The log with 0ms delay is the same as the log with 20ms delay, but we can see that the value of cwnd has not changed at 40ms. We see that the trained model uses the simulation environment generated by mahimahi. The maximum bandwidth of this environment seems to be only 108Mbps. This is very different from our 1000Mbps environment. Do we need to retrain based on our environment?Looking forward to your answer, thank you very much.

**Comment by odelalleau** [comment]
HI @chengcheng8632, based on your question "Do we need to retrain based on our environment?" I assume that currently you are evaluating the same model under various network settings? This is something that may not work very well indeed -- see the paragraph in the paper "One challenge we faced is generalization when training jointly over networks with widely different ranges of throughput and delay". Training models that are more robust to varying network conditions is a topic of future research on our end.
