### ISSUE TITLE
Questions about train trace

### ISSUE THREAD

**Issue by chengcheng8632** [facebookresearch/mvfst-rl#21]
Dear Author:
        I have a question about the training trace. I use vs code to find that the data in 12Mbps.trace are all numbers. How these numbers are generated, may I ask the author if he has any knowledge of this? Looking forward to your answer, thank you very much.

**Comment by viswanathgs** [comment]
Those are copied directly from Pantheon: https://github.com/StanfordSNR/observatory/tree/master/traces. You could try https://groups.google.com/forum/#!forum/pantheon-stanford.
