### ISSUE TITLE
Question about build grpc

### ISSUE THREAD

**Issue by chengcheng8632** [facebookresearch/mvfst-rl#24]
Dear Author:
Hello, I encountered grpc issues while rebuilding the mvfst-rl environment. Could you say that the manual installation is to install protobuf located at install_grpc.sh yourself? Or go to Google how to install grpc? If it is manually installed, does the conda install protobuf in setup.sh conflict with the manual installation? Also, is grpc installed in the environment of mvfst-rl? I toss for a day and still haven't solved the problem. Hope to get your help, thank you very much.

**Comment by odelalleau** [comment]
Hi @chengcheng8632, can you please provide the exact error you are facing?

**Comment by chengcheng8632** [comment]
Hello,@odelalleau:
I always get this error when installing grpc:
"Package protobuf was not found in the pkg-config search path.Perhaps you should add the directory containing `protobuf.pc 'to the PKG_CONFIG_PATH environment variable. No package 'protobuf' found ". 
I want to know if the path of pkg_config_path was manually given? Does this path point to the virtual environment? Looking forward to your answer, thank you very much!

**Comment by odelalleau** [comment]
Ok thanks, can you please try to edit `third-party/install_grpc.sh` and add this line before the `make` statements:
```
export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}
```

Let me know if that helps!

**Comment by odelalleau** [comment]
Hi @chengcheng8632,
I just wanted to check if the change I suggested fixed your problem? (if yes I'll make sure it's included in a future update of the code).
Thanks!

**Comment by chengcheng8632** [comment]
Hello,@odelalleau:
Your suggestion solved my problem (by the way, my system is ubuntu18.04.4)，thanks！
