### ISSUE TITLE
How to start-up remote mode

### ISSUE THREAD

**Issue by z6833** [facebookresearch/mvfst-rl#26]
Hello, thanks for your interesting works . 
I find that when I run commands for training , `mvfst-rl`will read the content in file `experiment.yml`. Then the command `common_param_set: >-local --data-dir {data_dir} --pkill-cleanup` will start-up the `local mode` of `pantheon` and do the whole trainning .
My question is that what should I do if I wanted to use `remote mode` of `pantheon`？I can not find the port that `mvfst-rl` start-up pantheon's remote mode for training . Is there anything I missed, or I should complete this myself ？Looking forward to your reply. Thanks so much.

**Comment by viswanathgs** [comment]
We haven't set mvfst-rl to work with pantheon remote mode yet. Could you expand on your use case?
