### ISSUE TITLE
AttributeError: module 'nest' has no attribute 'map'

### ISSUE THREAD

**Issue by Zongshen** [facebookresearch/mvfst-rl#35]
Hello. Appreciate your previous suggestions and help in building project.
The final lines of the output after I run `./setup.sh` are shown as belows.
`-- Generating done`
`-- Build files have been written to: /home/zongshen/Project/mvfst-rl/_build/build`
`+ make -j 24`
`[  6%] Building CXX object third-party/CMakeFiles/rpcenv_pb.dir/torchbeast/torchbeast/rpc.grpc.pb.cc.o`
`[ 13%] Building CXX object third-party/CMakeFiles/rpcenv_pb.dir/torchbeast/torchbeast/rpc.pb.cc.o`
`[ 20%] Linking CXX static library librpcenv_pb.a`
`[ 20%] Built target rpcenv_pb`
`[ 26%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/NetworkState.cpp.o`
`[ 33%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/CongestionControlFixedCwndEnv.cpp.o`
`[ 40%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/CongestionControlLocalEnv.cpp.o`
`[ 46%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/CongestionControlEnv.cpp.o`
`[ 53%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/CongestionControlEnvConfig.cpp.o`
`[ 60%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/RLBandwidthSampler.cpp.o`
`[ 66%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/RLCongestionController.cpp.o`
`[ 73%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/CongestionControlRPCEnv.cpp.o`
`[ 80%] Building CXX object congestion_control/CMakeFiles/rl_congestion_control.dir/Utils.cpp.o`
`[ 86%] Linking CXX static library librl_congestion_control.a`
`[ 86%] Built target rl_congestion_control`
`[ 93%] Building CXX object traffic_gen/CMakeFiles/traffic_gen.dir/main.cpp.o`
`[100%] Linking CXX executable traffic_gen`
`[100%] Built target traffic_gen`
`+ echo -e 'Done building.'`
`Done building.`
In this case I assume that the building with training support is done correctly.
However, when I run 
`python3 -m train.train \`
`mode=train \`
`total_steps=1_000_000 \`
`num_actors=40 \`
`hydra.run.dir=/tmp/logs`
I got the following error saying that the module 'nest' has no attribute 'map'.
`[INFO:366242 pantheon_env:233 2022-03-11 01:24:31,743] Using all 18 jobs.`
`[INFO:366242 pantheon_env:184 2022-03-11 01:24:31,743] Launching 18 jobs over 40 threads for train.`
`[INFO:366242 pantheon_env:248 2022-03-11 01:24:31,751] Located python2 in /usr/bin`
`[INFO:366242 pantheon_env:115 2022-03-11 01:24:31,753] Thread: 0, episode: 0, experiment: 6, cmd: /home/zongshen/Project/mvfst-rl/_build/deps/pantheon/src/experiments/test.py local --data-dir /tmp/logs/train/train_tid0_run0_expt6 --pkill-cleanup --uplink-trace /home/zongshen/Project/mvfst-rl/train/traces/12mbps.trace --downlink-trace /home/zongshen/Project/mvfst-rl/train/traces/12mbps.trace --prepend-mm-cmds mm-delay 10 --extra-mm-link-args --uplink-queue=droptail --uplink-queue-args=packets=1 --downlink-queue=droptail --downlink-queue-args=packets=1 --schemes=mvfst_rl --run-times=1 --extra-sender-args="--cc_env_mode=remote --cc_env_rpc_address=unix:/tmp/rl_server_path_0 --cc_env_actor_id=0 --cc_env_job_id=6 --cc_env_model_file=/tmp/logs/traced_model.pt --cc_env_agg=time --cc_env_time_window_ms=100 --cc_env_fixed_window_size=10 --cc_env_use_state_summary=True --cc_env_history_size=20 --cc_env_norm_ms=100.0 --cc_env_norm_bytes=1000.0 --cc_env_actions=0,/2,-10,+10,*2 --cc_env_reward_log_ratio=True --cc_env_reward_throughput_factor=1.0 --cc_env_reward_throughput_log_offset=1e-05 --cc_env_reward_delay_factor=0.2 --cc_env_reward_delay_log_offset=1e-05 --cc_env_reward_packet_loss_factor=0.0 --cc_env_reward_packet_loss_log_offset=1e-05 --cc_env_reward_max_delay=True --cc_env_fixed_cwnd=10 --cc_env_min_rtt_window_length_us=10000000000 -v=1"`
`[DEBUG:366241 cmd:870 2022-03-11 01:24:31,810] Popen(['git', 'version'], cwd=/home/zongshen/Project/mvfst-rl, universal_newlines=False, shell=None, istream=None)`
`[DEBUG:366241 cmd:870 2022-03-11 01:24:31,817] Popen(['git', 'version'], cwd=/home/zongshen/Project/mvfst-rl, universal_newlines=False, shell=None, istream=None)`
`[DEBUG:366241 cmd:870 2022-03-11 01:24:31,825] Popen(['git', 'cat-file', '--batch-check'], cwd=/home/zongshen/Project/mvfst-rl, universal_newlines=False, shell=None, istream=<valid stream>)`
`[DEBUG:366241 cmd:870 2022-03-11 01:24:31,832] Popen(['git', 'diff', '--cached', '--abbrev=40', '--full-index', '--raw'], cwd=/home/zongshen/Project/mvfst-rl, universal_newlines=False, shell=None, istream=None)`
`[DEBUG:366241 cmd:870 2022-03-11 01:24:31,837] Popen(['git', 'diff', '--abbrev=40', '--full-index', '--raw'], cwd=/home/zongshen/Project/mvfst-rl, universal_newlines=False, shell=None, istream=None)`
`$ /home/zongshen/Project/mvfst-rl/_build/deps/pantheon/src/experiments/git_summary.sh
Testing scheme mvfst_rl for experiment run 1/1...`
`$ /home/zongshen/Project/mvfst-rl/_build/deps/pantheon/src/wrappers/mvfst_rl.py run_first`
`[INFO:366241 learner:578 2022-03-11 01:24:32,011] Writing logs to /tmp/logs/train/logs.tsv`
`[INFO:366241 pantheon_env:233 2022-03-11 01:24:32,012] Using all 18 jobs.`
`[tunnel server manager (tsm)] $ python /home/zongshen/Project/mvfst-rl/_build/deps/pantheon/src/experiments/tunnel_manager.py`
`Process Process-2:`
`Traceback (most recent call last):`
`  File "/home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap`
`    self.run()`
`  File "/home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/multiprocessing/process.py", line 108, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "/home/zongshen/Project/mvfst-rl/train/learner.py", line 1108, in main`
`    return _main(`
`  File "/home/zongshen/Project/mvfst-rl/train/learner.py", line 1154, in _main`
`    learner_loop(flags, rank, barrier, gossip_buffer, stop_event)`
`  File "/home/zongshen/Project/mvfst-rl/train/learner.py", line 603, in learner_loop`
`    dummy_env_output = nest.map(`
`AttributeError: module 'nest' has no attribute 'map'`
`[2022-03-11 01:24:32,065][root][INFO] - Stop event #0 set, will kill corresponding env (pid=366242)`
`[2022-03-11 01:24:32,201][root][INFO] - Done training.`
`Error executing job with overrides: ['mode=train', 'total_steps=1_000_000', 'num_actors=40']`
`Traceback (most recent call last):`
`  File "/home/zongshen/Project/mvfst-rl/train/train.py", line 319, in main`
`    test(flags)`
`  File "/home/zongshen/Project/mvfst-rl/train/train.py", line 244, in test`
`    init_logdirs(flags)`
`  File "/home/zongshen/Project/mvfst-rl/train/train.py", line 95, in init_logdirs`
`    assert os.path.exists(`
`AssertionError: Checkpoint /tmp/logs/checkpoint.tar missing in test mode`

`Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

Could you please help me with this?
Thank you.

**Comment by odelalleau** [comment]
Hmm, that's weird, can you check what the following would print (in your mvfst-rl conda env):
```
python -c "import nest ; print(nest.__file__) ; print(nest.map)"
```

**Comment by Zongshen** [comment]
Hi, I tried the command in my mvfst-rl conda env and it still shows no attribute as following:

`(mvfst-rl) ➜  mvfst-rl git:(main) python -c "import nest ; print(nest.__file__) ; print(nest.map)"`
`[INFO] [2022.3.11 22:47:55 /home/conda/feedstock_root/build_artifacts/nest-simulator_1636957219167/work/nestkernel/rng_manager.cpp:217 @ Network::create_rngs_] : Creating default RNGs`
`[INFO] [2022.3.11 22:47:55 /home/conda/feedstock_root/build_artifacts/nest-simulator_1636957219167/work/nestkernel/rng_manager.cpp:260 @ Network::create_grng_] : Creating new default global RNG`
`              -- N E S T --`
 ` Copyright (C) 2004 The NEST Initiative`
` Version: nest-2.20.2`
` Built: Nov 15 2021 06:23:37`
` This program is provided AS IS and comes with`
` NO WARRANTY. See the file LICENSE for details.`
` Problems or suggestions?`
`   Visit https://www.nest-simulator.org`
` Type 'nest.help()' to find out more about NEST.`
`/home/zongshen/anaconda3/envs/mvfst-rl/lib64/python3.8/site-packages/nest/__init__.py`
`Traceback (most recent call last):`
`  File "<string>", line 1, in <module>`
`AttributeError: module 'nest' has no attribute 'map'`

**Comment by odelalleau** [comment]
Interesting, looks like you somehow have another library installed with the same name « nest », I wonder where it comes from. The one you want to use is from third_party/torchbeast/third_party/nest (I think, I can’t check now, let me know if you can’t figure out how to install it and I’ll look it up later)

**Comment by Zongshen** [comment]
I looked into the output trace when I run `./setup.sh` and the following part is the output when installing 'nest' module.
It seems that it processes the `third_party/torchbeast/third_party/nest` for the installation, but I still cannot figure out what to do with it.

`Processing ./third_party/nest`
`  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.`
`   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.`
`Requirement already satisfied: pybind11>=2.4 in /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages (from nest==0.0.6) (2.9.1)`
`Building wheels for collected packages: nest`
`  Building wheel for nest (setup.py): started`
`  Building wheel for nest (setup.py): finished with status 'done'`
`  Created wheel for nest: filename=nest-0.0.6-cp38-cp38-linux_x86_64.whl size=1454027 sha256=e69711c522ce6b6a034c20136dbbd66e113c5f3d76b5772c7d705cf541d55457`
`  Stored in directory: /tmp/pip-ephem-wheel-cache-9m3apcz_/wheels/ec/f0/7d/5eff4159637b0092704f3074107a50abdf17995a1b0385406d`
`Successfully built nest`
`Installing collected packages: nest`
`  Attempting uninstall: nest`
`    Found existing installation: nest 0.0.6`
`    Uninstalling nest-0.0.6:`
`      Successfully uninstalled nest-0.0.6`
`Successfully installed nest-0.0.6`

I also went to the `third_party/torchbeast/third_party/nest` directory and manually executed the nest install command as "https://github.com/facebookresearch/torchbeast/tree/main/nest" shows.
However, it still does not work for me.
Could you please help me with this?

**Comment by Zongshen** [comment]
Also, the `python -c "import nest ; print(nest.__file__) ; print(nest.map)"` command seems to only work when I am in the directory of `/home/zongshen/Project/mvfst-rl/third-party/torchbeast/third_party/nest/build/lib.linux-x86_64-3.8`.
The output is:
`(mvfst-rl) ➜  lib.linux-x86_64-3.8 git:(b417b4b) python -c "import nest ; print(nest.__file__) ; print(nest.map)"`
`/home/zongshen/Project/mvfst-rl/third-party/torchbeast/third_party/nest/build/lib.linux-x86_64-3.8/nest/__init__.py`
`<built-in method map of PyCapsule object at 0x7f68f2b47810>`

However, when I switch to other directories, this command will go for that wrong version of PyPi "nest 0.0.6" module instead of going for this correct one. (I am assuming the output above is the expected output with correct installation.)

**Comment by odelalleau** [comment]
> I also went to the `third_party/torchbeast/third_party/nest` directory and manually executed the nest install command as "https://github.com/facebookresearch/torchbeast/tree/main/nest" shows. However, it still does not work for me.

Can you paste the last few lines of this output's command? (the one that should show the path it is being installed into)

Worst case scenario, I guess you can add `/home/zongshen/Project/mvfst-rl/third-party/torchbeast/third_party/nest/build/lib.linux-x86_64-3.8` at the beginning of your PYTHONPATH variable and it should work. Though it's still unclear to me how you ended up in that situation...

**Comment by Zongshen** [comment]
The lines related to paths in the installing output are shown as below. The final destination of `__init__.py` are shown in the last few lines.

`(mvfst-rl) ➜  nest git:(b417b4b) CXX=c++ pip install . -vv`
`Using pip 21.2.4 from /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/pip (python 3.8)`
`Non-user install because site-packages writeable`
`Created temporary directory: /tmp/pip-ephem-wheel-cache-xwz0ryf3`
`Created temporary directory: /tmp/pip-req-tracker-8uzrwny5`
`Initialized build tracking at /tmp/pip-req-tracker-8uzrwny5`
`Created build tracker: /tmp/pip-req-tracker-8uzrwny5`
`Entered build tracker: /tmp/pip-req-tracker-8uzrwny5`
`Created temporary directory: /tmp/pip-install-nyd_dxsh`
`Processing /home/zongshen/Project/mvfst-rl/third-party/torchbeast/third_party/nest`
`  Created temporary directory: /tmp/pip-req-build-jpucg3ug`
`  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.`
`   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.`
`  Added file:///home/zongshen/Project/mvfst-rl/third-party/torchbeast/third_party/nest to build tracker '/tmp/pip-req-tracker-8uzrwny5'`
...
...
`Created temporary directory: /tmp/pip-unpack-9zq8fcgg`
`Building wheels for collected packages: nest`
`  Created temporary directory: /tmp/pip-wheel-dd1a_sn6`
`  Building wheel for nest (setup.py) ...   Destination directory: /tmp/pip-wheel-dd1a_sn6`
...
...
`  Created wheel for nest: filename=nest-0.0.6-cp38-cp38-linux_x86_64.whl size=1454633 sha256=9b73a08e4de46176fc07b7755b8b17dfb7ae0bf733b79735acf61260d2ca89e5`
`  Stored in directory: /tmp/pip-ephem-wheel-cache-xwz0ryf3/wheels/ec/f0/7d/5eff4159637b0092704f3074107a50abdf17995a1b0385406d`
`Successfully built nest`
`Installing collected packages: nest`
`  Attempting uninstall: nest`
`    Found existing installation: nest 0.0.6`
`    Uninstalling nest-0.0.6:`
`      Created temporary directory: /home/zongshen/anaconda3/envs/mvfst-rl/include/python3.8/~est`
`      Removing file or directory /home/zongshen/anaconda3/envs/mvfst-rl/include/python3.8/nest/`
`      Created temporary directory: /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/~est-0.0.6.dist-info`
`      Removing file or directory /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/nest-0.0.6.dist-info/`
`      Created temporary directory: /tmp/pip-uninstall-wcohw16g`
`      Removing file or directory /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/nest/__init__.py`
`      Removing file or directory /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/nest/__pycache__/__init__.cpython-38.pyc`
`      Removing file or directory /home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages/nest/_nest.cpython-38-x86_64-linux-gnu.so`
`      Successfully uninstalled nest-0.0.6`

`Successfully installed nest-0.0.6`
`Removed build tracker: '/tmp/pip-req-tracker-8uzrwny5'`

**Comment by odelalleau** [comment]
Ah, now that's funny, looks like the other `nest` is installed in `lib64`, while the correct one is installed in `lib`. I just double checked and I personally don't even have `lib64` in my own conda env... so I still wonder where this is coming from. But anyway, at least it gives a hint as to why you are seeing this crash, as I guess the `lib64` path takes precedence over the `lib` one.

So I can see two options:
1. Trying to figure out what is causing the installation of this weird `nest` library in `lib64` then try to avoid it
2. Or just work around it by adding `/home/zongshen/anaconda3/envs/mvfst-rl/lib/python3.8/site-packages` at the beginning of your `PYTHONPATH` (and hope nothing else breaks because of it)

**Comment by Zongshen** [comment]
No problem. I will look into the installation destination. As for the use, I think I can just add the path into the PYTHONPATH for my current use. 
Thank you again for your time and effort!
