### ISSUE TITLE
setup.sh --clean error

### ISSUE THREAD

**Issue by cczaqq** [facebookresearch/mvfst-rl#37]
Hello! Thank you for providing this highly integrated platform.
I tried to build the project in the conda environment with python 3.8 in Ubuntu 20.04LTS.
when I run ./setup.sh --clean, the following error occurs:

Collecting git+git://github.com/odelalleau/hydra.git@f07036a8f3895169e62d89ad653434291b994780
  Cloning git://github.com/odelalleau/hydra.git (to revision f07036a8f3895169e62d89ad653434291b994780) to /tmp/pip-req-build-t0400uu1
  Running command git clone -q git://github.com/odelalleau/hydra.git /tmp/pip-req-build-t0400uu1
  fatal: remote error：
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
WARNING: Discarding git+git://github.com/odelalleau/hydra.git@f07036a8f3895169e62d89ad653434291b994780. Command errored out with exit status 128: git clone -q git://github.com/odelalleau/hydra.git /tmp/pip-req-build-t0400uu1 Check the logs for full command output.
ERROR: Command errored out with exit status 128: git clone -q git://github.com/odelalleau/hydra.git /tmp/pip-req-build-t0400uu1 Check the logs for full command output.

May I know how to solve this problem?
Thank you again.

**Comment by odelalleau** [comment]
Can you replace both instances of `git+git` in `setup.sh` with `git+https` and let me know if this works for you?

**Comment by cczaqq** [comment]
When I run with git+https, I can get code.

Thanks a lot!

**Comment by odelalleau** [comment]
Closing issue since the workaround above seems to be working
