### ISSUE TITLE
Test model error

### ISSUE THREAD

**Issue by cczaqq** [facebookresearch/mvfst-rl#39]
Hello! Thank you for providing this highly integrated platform.
I tried to build the project in the conda environment with python 3.8 in Ubuntu 20.04LTS.
I wanted to test the model.
After I finished "./setup.sh --clean", and "python3 -m train.train mode=test base_logdir=/tmp/logs", the following error occured:

AssertionError: Checkpoint /tmp/logs/checkpoint.tar missing in test mode

It seems checkpoint.tar was missing. So how to generate checkpoint.tar?

Thanks a lot.

**Comment by odelalleau** [comment]
Hi,

checkpoint.tar is generated in train mode: you need to train a model before you can test it.

**Comment by cczaqq** [comment]
Thank you!
