### ISSUE TITLE
Questions with evaluation

### ISSUE THREAD

**Issue by cczaqq** [facebookresearch/mvfst-rl#41]
Hi,

     When I evaluate a trained model using the script "python3 -m train.train mode=test base_logdir=/tmp/logs", there are errors like this:
"
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/jerry/mvfst-rl/run/2022-05-11_17-21-50'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jerry/.conda/envs/mvfst-rl/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/checkpoint/jerry/mvfst-rl/run'

During handling of the above exception, another exception occurred:
"

After training the model, the checkpoint.tar file is in /tmp/logs/, not /checkpoint/jerry/mvfst-rl/. Why does it go to /checkpoint/jerry/mvfst-rl/run/ to find the checkpoint.tar?

And what are the use of checkpoint.tar, traced_model.pt and traced_model.flags.pkl? Is checkpoint.tar a file with parameters? And traced_model.pt a model file? I'm confused.

Thank you!

**Comment by odelalleau** [comment]
I don't remember for sure but maybe it still needs somehow to create the Hydra run dir => try to change it in config.yaml (to a path that exists somewhere on your drive) to see if that fixes it.

**Comment by cczaqq** [comment]
Thank you！The problem is solved.
